### ISSUE TITLE
Console docker image is buggy

### ISSUE THREAD

**Issue by tanimientras** [pandorafms/pandorafms#93]
While trying to deploy pandorafms/pandorafms-console:7 we are getting this trace several times:

```
Tue Nov 14 13:24:56 CET 2017 - waiting for MySQL connection...
HOSTNAME=626d253987d8
MYSQL_PORT_3306_TCP_PORT=3306
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/root
MYSQL_PORT_3306_TCP_ADDR=mysql
_=/usr/bin/env
```

Although entrypoint.sh script contains:
```
#wait for mysql
i=0
while ! nc $MYSQL_PORT_3306_TCP_ADDR $MYSQL_PORT_3306_TCP_PORT >/dev/null 2>&1 < /dev/null; do
  i=`expr $i + 1`
  if [ $i -ge $MYSQL_LOOPS ]; then
    echo "$(date) - MySQL still not reachable, giving up"
    env
    exit 1
  fi
  echo "$(date) - waiting for MySQL connection..."
  env
  sleep 5
done
```
seems nc is not actually installed on image.

**Comment by TheMiller2015** [comment]
Hello, this problem exists still today. So all the docker-images are not usable. Any hint, what we can do? thanks!

**Comment by TheMiller2015** [comment]
So, I'll try to share my solution. Maybe the pandora-team can check this answer too. I have it running now. It used my very own db-docker image (not the one of pandora), built new pandora-images with docker-compose, started the console, executed the sql-files (pandoradb.sql and pandoradb_data.sql from the console-container) againt my mysql-db and then have a running installation. Here are my docker-files right now:

````
pandora:
    build: ./builds/pandora
    container_name: pandora
    environment:
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - PANDORA_DB_HOST=mysql
      - PANDORA_DB_USER=pandora
      - PANDORA_DB_PASSWORD=xxxxxxxxxxxxxxx
      - PANDORA_DB_NAME=pandora
    links:
      - mysql:mysql
    ports:
      - 41121:41121

  pandora-console:
    build: ./builds/pandora-console
    container_name: pandora-console
    environment:
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - PANDORA_DB_HOST=mysql
      - PANDORA_DB_USER=pandora
      - PANDORA_DB_PASSWORD=xxxxxxxxxxxx
      - PANDORA_DB_NAME=pandora
    links:
      - mysql:mysql
    ports:
      - 86:80
      - 8022:8022
      - 8023:8023
````
Please note the ENV_VARS "MYSQL_PORT_3306_TCP_ADDR" and "MYSQL_PORT_3306_TCP_PORT" since they seem to be mandatory and checked at container-start. Without these, I got no db-connection just "waiting for mysql connection".

Ok, and here are the two Dockerfiles that are getting build when running "docker-compose build up -d"....
The only difference is, that I install the program "nc" with that the pandora-entrypoint-file checks the db-connection. We assume, that they did forget to install this program, so we do it on our own while deriving from the latests Dockerfiles.

````
FROM pandorafms/pandorafms-server:7
RUN yum -y install nc
````
````
FROM pandorafms/pandorafms-console:7
RUN yum -y install nc
````

So, hope that helps anyone or indeed the pandora-team. But I have one question myself: Should/Can I map any volumes, especially for the pandora-console-container? If yes, which ones? E.g. for /var/www/html/pandora_console?

Thanks guys and girls.
