### ISSUE TITLE
Pandora server 7 dockerized doesn't work

### ISSUE THREAD

**Issue by tanimientras** [pandorafms/pandorafms#95]
We haven't been able to run pandorafms/pandorafms-server:7 due to logs complaining about:

```
...
User pandora does exist, make sure the SSH directories are correct
Giving proper permission to /var/spool/pandora
No web server user found, some functionality might not perform correctly
Creating setup directory in /etc/pandora
cp conf/pandora_server.conf.new /etc/pandora/pandora_server.conf
Installing Pandora Server manual
Copying the daemon script into /etc/init.d
Linking startup script to /etc/rc.d/rc3.d/S90pandora_server
Creating logrotate.d entry for Pandora FMS log management
Copying the daemon script into /etc/init.d
Linking startup script to /etc/rc.d/rc3.d/S80tentacle_serverd
Installing Tentacle Server manual
Creating Pandora FMS distribution directory in /usr/share/pandora_server
Creating the Cron script to run Pandora DB tool each hour

Now you have to edit your /etc/pandora/pandora_server.conf file to change the database password (default is pandora) with the one set in include/config.php of your Pandora FMS Console.
After setting password you can start your Pandora FMS Server!!
Starting ntpd: Starting crond: [  OK  ]
[  OK  ]
Starting postfix: 
Pandora FMS Server 7.0NG.715 Build 171114 Copyright (c) 2004-2015 ArticaST
This program is OpenSource, licensed under the terms of GPL License version 2.
You can download latest versions and documentation at http://www.pandorafms.org 

 [*] Pandora FMS Enterprise module not available.
 [*] Netflow daemon disabled.
 [*] Starting Pandora FMS Data Server.
 [*] Starting Pandora FMS Network Server.
 [*] Starting Pandora FMS Recon Server.
 [*] Starting Pandora FMS WMI Server.
 [*] Starting Pandora FMS Plugin Server.
[FAILED]
Tentacle Server is now running with PID 235
 [E] Unhandled error in "036421bad730". See more information in logfiles at '/var/log/pandora' 

 Error description:

DBD::mysql::db do failed: Field 'parent_module_id' doesn't have a default value at /usr/lib/perl5/PandoraFMS/DB.pm line 810.

 [E] Unhandled error in "036421bad730". See more information in logfiles at '/var/log/pandora' 

 Error description:

15 at /usr/lib/perl5/PandoraFMS/DB.pm line 820.

 [E] Unhandled error in "036421bad730". See more information in logfiles at '/var/log/pandora' 

 Error description:

15 at /usr/lib/perl5/PandoraFMS/DB.pm line 820.

^C [*] Shutting down 036421bad730(received signal)...
...

[root@036421bad730 pandora_server]# tail /var/log/pandora/pandora_server.error 
2017-11-14 14:27:52 - 036421bad730 Starting Pandora FMS Server. Error logging activated.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4696.
DBD::mysql::db do failed: Field 'parent_module_id' doesn't have a default value at /usr/lib/perl5/PandoraFMS/DB.pm line 810.
2017-11-14 14:37:01 - 036421bad730 Starting Pandora FMS Server. Error logging activated.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4696.
DBD::mysql::db do failed: Field 'parent_module_id' doesn't have a default value at /usr/lib/perl5/PandoraFMS/DB.pm line 810.

[root@036421bad730 pandora_server]# tail /var/log/pandora/pandora_server.log 
2017-11-14 14:37:06 036421bad730 [V1] Pandora FMS Server '036421bad730' unhandled error.
2017-11-14 14:37:06 036421bad730 [V1] [E] '036421bad730': 15 at /usr/lib/perl5/PandoraFMS/DB.pm line 820.

2017-11-14 14:37:06 036421bad730 [V1] Pandora FMS Server '036421bad730' unhandled error.
2017-11-14 14:37:07 036421bad730 [V1] [E] '036421bad730': 15 at /usr/lib/perl5/PandoraFMS/DB.pm line 820.

2017-11-14 14:37:07 036421bad730 [V1] Pandora FMS Server '036421bad730' unhandled error.
2017-11-14 14:37:07 036421bad730 [V1] Pandora FMS Server restarting () in 60 seconds.
2017-11-14 14:37:16 036421bad730 [V1] Pandora FMS Server '036421bad730' Shutdown by signal 
```

**Comment by tanimientras** [comment]
After reviewing startup process, we think we have found some issues with default data being imported.

```
[root@af48308299bf /]# /usr/bin/pandora_server /etc/pandora/pandora_server.conf 

Pandora FMS Server 7.0NG.715 Build 171115 Copyright (c) 2004-2015 ArticaST
This program is OpenSource, licensed under the terms of GPL License version 2.
You can download latest versions and documentation at http://www.pandorafms.org 

2017-11-15 13:05:12 monitor [V1] Launching 7.0NG.715 171115
2017-11-15 13:05:12 monitor [V1] Config options: Logfile at /dev/stdout, Basepath is /etc/pandora/pandora_server.conf, Checksum is 0, Master is 1, SNMP Console is 0, Server Threshold at 5 sec, verbosity at 3, Alert Threshold at 60, ServerName is 'monitor'
 [*] Pandora FMS Enterprise module not available.
2017-11-15 13:05:12 monitor [V1]  [*] Pandora FMS Enterprise module not available.
2017-11-15 13:05:12 - monitor Starting Pandora FMS Server. Error logging activated.
2017-11-15 13:05:12 monitor [V1]  [*] Netflow daemon disabled.
 [*] Netflow daemon disabled.
 [*] Starting Pandora FMS Data Server.
 [*] Starting Pandora FMS Network Server.
 [*] Starting Pandora FMS Recon Server.
 [*] Starting Pandora FMS WMI Server.
 [*] Starting Pandora FMS Plugin Server.
2017-11-15 13:05:13 monitor [V3] Warmup mode for unknown modules started.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4702.
DBD::mysql::db do failed: Field 'parent_module_id' doesn't have a default value at /usr/lib/perl5/PandoraFMS/DB.pm line 810.
2017-11-15 13:05:17 monitor [V1] [E] 'monitor': DBD::mysql::db do failed: Field 'parent_module_id' doesn't have a default value at /usr/lib/perl5/PandoraFMS/DB.pm line 810.

2017-11-15 13:05:17 monitor [V1] Pandora FMS Server 'monitor' unhandled error.
 [E] Unhandled error in "monitor". See more information in logfiles at '/var/log/pandora' 

 Error description:

DBD::mysql::db do failed: Field 'parent_module_id' doesn't have a default value at /usr/lib/perl5/PandoraFMS/DB.pm line 810.

2017-11-15 13:05:17 monitor [V1] [E] 'monitor': 15 at /usr/lib/perl5/PandoraFMS/DB.pm line 820.

2017-11-15 13:05:17 monitor [V1] Pandora FMS Server 'monitor' unhandled error.
 [E] Unhandled error in "monitor". See more information in logfiles at '/var/log/pandora' 

 Error description:

15 at /usr/lib/perl5/PandoraFMS/DB.pm line 820.

2017-11-15 13:05:18 monitor [V1] [E] 'monitor': 15 at /usr/lib/perl5/PandoraFMS/DB.pm line 820.

2017-11-15 13:05:18 monitor [V1] Pandora FMS Server 'monitor' unhandled error.
 [E] Unhandled error in "monitor". See more information in logfiles at '/var/log/pandora' 

 Error description:

15 at /usr/lib/perl5/PandoraFMS/DB.pm line 820.

2017-11-15 13:05:18 monitor [V1] Pandora FMS Server restarting () in 60 seconds.
```

**Comment by mattjohn22** [comment]
I've run into this same exact problem as well. Any update on it?

**Comment by TheMiller2015** [comment]
Stuck with the same problem. Please help us! I have no idea and I don't want to alter the db myself.... thanks

**Comment by TheMiller2015** [comment]
I altered the db like this
````ALTER TABLE `tagente_modulo` CHANGE `parent_module_id` `parent_module_id` INT(10) UNSIGNED NOT NULL DEFAULT '0';````
Don't know, what this will cause in future, but for now it works. The docker-containers are in an alpha-state. Sorry for mentioning this, but it's the sad truth. But the software (when it works) is pretty awesome.

Maybe some devs or team-members can say sth. about "my" database-change. Thanks in advance.

**Comment by slerena** [comment]
We're watching the thread, and I hope tomorrow someone from the dev team will try to help to fix this issues. This branch was "outdated" (forgot) and we were keeping other docker images, but we will redirect the effort to keep this also updated.

Thanks for the "pretty awesome" part :-))

**Comment by nramon** [comment]
Hi @tanimientras, @mattjohn2, and @TheMiller2015,

Thanks for the feedback and suggestions. Those docker images were not being maintained. The original contributor is not around anymore and we never got to fixing them. Sorry about that.

The build process relied on multiple scripts and dynamically generated Dockerfiles. I can look for them and add them to the repo if you're interested. We just don't have the time to maintain them.

I've added added a new [Dockerfile](https://github.com/pandorafms/pandorafms/tree/develop/extras/docker) to the repo instead to build a single Pandora FMS image containing the server, the console and the database. The new [image](https://hub.docker.com/r/pandorafms/pandorafms/) will be automatically rebuilt everyday, and it can be run from the same [script](https://wiki.pandorafms.com/index.php?title=Pandora:Documentation_en:Installing#Installation_under_Docker).

Regards.

**Comment by TheMiller2015** [comment]
Hi thanks for your answer and reviving theses containers. Didn't test theses containers now, but in the near future, I'll do so while setting up a new instance. Thx.

**Comment by marcelo-ochoa** [comment]
I am just checkout github repo and I found two minors tweaks for Docker images:

- MySQL docker image create_pandoradb.sh fails to alter .sql fail due incorrect file permitions
- Pandora console do not support SSL (it is requires to work behind a load-balancer
For the first problem the diff is:
```
[mochoa@pocho pandorafms]$ git diff pandora_console/DB_Dockerfile
diff --git a/pandora_console/DB_Dockerfile b/pandora_console/DB_Dockerfile
index eb6465f..4b4b0b3 100644
--- a/pandora_console/DB_Dockerfile
+++ b/pandora_console/DB_Dockerfile
@@ -5,10 +5,11 @@ WORKDIR /pandorafms/pandora_console
 
 ADD pandoradb.sql /docker-entrypoint-initdb.d
 ADD pandoradb_data.sql /docker-entrypoint-initdb.d
+RUN chown 999:999 /docker-entrypoint-initdb.d/pandoradb.sql /docker-entrypoint-initdb.d/pandoradb_data.sql
 
 ENV MYSQL_DATABASE=pandora
 
 RUN echo " \n\
-sed -i \"1iUSE \$MYSQL_DATABASE\" /docker-entrypoint-initdb.d/pandoradb.sql \n\
-sed -i \"1iUSE \$MYSQL_DATABASE\" /docker-entrypoint-initdb.d/pandoradb_data.sql \n\
+cp /docker-entrypoint-initdb.d/pandoradb.sql /tmp/ee && sed -i \"1iUSE \$MYSQL_DATABASE\" /tmp/ee && cat /tmp/ee > /docker-entrypoint-initdb.d/pandoradb.sql \n\
+cp /docker-entrypoint-initdb.d/pandoradb_data.sql /tmp/ee && sed -i \"1iUSE \$MYSQL_DATABASE\" /tmp/ee && cat /tmp/ee > /docker-entrypoint-initdb.d/pandoradb_data.sql \n\
 " >> /docker-entrypoint-initdb.d/create_pandoradb.sh
```
For the SSL support support here the diff:
```
[mochoa@pocho pandorafms]$ git diff pandora_console/Dockerfile
diff --git a/pandora_console/Dockerfile b/pandora_console/Dockerfile
index ccbcef4..7fc947b 100644
--- a/pandora_console/Dockerfile
+++ b/pandora_console/Dockerfile
@@ -45,13 +45,14 @@ RUN yum install -y \
        php-zip \ 
        nmap \
        net-snmp-utils \
+       mod_ssl \
        xprobe2
 
 #Clone the repo
 RUN git clone -b develop https://github.com/pandorafms/pandorafms.git /tmp/pandorafms
 
 #Exposing ports for: HTTP, SNMP Traps, Tentacle protocol
-EXPOSE 80 162/udp 41121
+EXPOSE 80 443 162/udp 41121
 
 # Simple startup script to avoid some issues observed with container restart
 ADD docker_entrypoint.sh /entrypoint.sh
```
with SSL support docker-compose.yml sample with haproxy load balancer look like:
```
  web:
    image: registry.exa.unicen.edu.ar:443/slab/pandora_console:7
    hostname: monitoring.exa.unicen.edu.ar
    volumes:
       - web_certs:/etc/ssl/certs:ro
       - web_conf:/etc/httpd/conf.d:ro
    depends_on:
      - mysql
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      VIRTUAL_HOST: "https://monitoring.exa.unicen.edu.ar"
      SERVICE_PORTS: "443"
      HEALTH_CHECK: "check ssl verify none"
      PANDORA_DB_HOST: mysql
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      PANDORA_DB_NAME: pandora
    networks:
      net:
        aliases:
          - pandorafms-console
      rproxy:
        aliases:
          - monitoring
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
```
If you need a PR, just tell me and I can create clone of git repo for doing that.
Best regards, Marcelo.

**Comment by nramon** [comment]
Hola, Marcelo. Thank you for the patches. I've fixed both issues, but feel free to submit a PR anytime. Like I said, we are not likely to maintain separate Dockerfiles for each component. We'll try to keep a single Dockerfile up to date instead.

**Comment by marcelo-ochoa** [comment]
Hola Ramón, thanks for accepting this minor patch.
Actually I have a plan to submit a [PR](https://github.com/pandorafms/pandorafms/compare/develop...marcelo-ochoa:develop) with these main benefits:

- 3 separate containers
- small size of the images 578MB/609MB versus 1.30Gb oldest one
- update to MySQL 5.7, may be compatible with Maria DB
- separate functionality for cron jobs (align with Docker best practices)
- configurable SMTP host/port, is better and recommendable in Docker postfix in a separate container
I know that one Docker for all is a simple deployment option, but for production Docker Swarn scenery is better an stack like this:
```
# Environment variables MYSQL_DATABASE_PASSWORD=StrongPwd1
# Environment variables MYSQL_ROOT_PWD=StrongPwd2
# Required external configs pandora_console_ssl to enable ssl support
version: '3.3'

services:
  mysql:
    image: slab/pandorafms-mysql:v7.0NG.722.7600
    hostname: mysql
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: pandora
      MYSQL_USER: pandora
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD} 
      MYSQL_ROOT_HOST: "%"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      net:
        aliases:
          - mysql
  server:
    image: slab/pandorafms-server:v7.0NG.722.7600
    hostname: pandorafms-server
    volumes:
       - web_plugin:/var/www/html/pandora_console/attachment/plugin
    depends_on:
      - mysql
    ports:
      - "41121:41121"
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      PANDORA_DB_HOST: mysql
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      PANDORA_DB_NAME: pandora
      PANDORA_SMTP_HOST: smtphost.mydomain.tld
      PANDORA_SMTP_PORT: 25
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      net:
        aliases:
          - pandorafms-server
  cron:
    image: slab/pandorafms-server:v7.0NG.722.7600
    command: /run_cron.sh
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      PANDORA_DB_HOST: mysql
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      PANDORA_DB_NAME: pandora
      PANDORA_SMTP_HOST: smtphost.mydomain.tld
      PANDORA_SMTP_PORT: 25
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    networks:
      net:
  web:
    image: slab/pandorafms-console:v7.0NG.722.7600
    hostname: mon.mydomain.tld
    volumes:
       - web_certs:/etc/ssl/certs:ro
       - web_plugin:/var/www/html/pandora_console/attachment/plugin
    depends_on:
      - mysql
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      VIRTUAL_HOST: "https://mon.mydomain.tld"
      SERVICE_PORTS: "443"
      HEALTH_CHECK: "check ssl verify none"
      PANDORA_DB_HOST: mysql
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      PANDORA_DB_NAME: pandora
    networks:
      net:
        aliases:
          - pandorafms-console
      rproxy:
        aliases:
          - monitoring
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    configs:
      - source: pandora_console_ssl
        target: /etc/httpd/conf.d/ssl.conf
        uid: '0'
        gid: '0'
        mode: 0644
volumes:
    db_data:
      driver: local
      driver_opts:
        type: nfs
        o: addr=NFS_server_or_NAS,rw,intr,hard,timeo=600,wsize=32768,rsize=32768,vers=3,tcp
        device: ":/docker/stacks/mon/db"
    web_certs:
      driver: local
      driver_opts:
        type: nfs
        o: addr=NFS_server_or_NAS,rw,intr,hard,timeo=600,wsize=32768,rsize=32768,vers=3,tcp
        device: ":/docker/stacks/letsencrypt/certs"
    web_plugin:
      driver: local
      driver_opts:
        type: nfs
        o: addr=NFS_server_or_NAS,rw,intr,hard,timeo=600,wsize=32768,rsize=32768,vers=3,tcp
        device: ":/docker/stacks/mon/plugin"
networks:
    net:
    rproxy:
        external:
            name: reverse_proxy
configs:
    pandora_console_ssl:
        external: true
```
In a separate stacks there is a Load Balancer using [HAProxy](https://store.docker.com/community/images/dockercloud/haproxy) which expose http/https access, [Swarm scheduler](https://store.docker.com/community/images/rayyanqcri/swarm-scheduler) for running Pandora Jobs and a [LetsEncrypt](https://store.docker.com/community/images/linuxserver/letsencrypt) stack for registering and renewing certificates.
Best regards, Marcelo.
